### ISSUE TITLE
Variant alias (@spice.as) does not work with variant with arguments

### ISSUE THREAD

**Issue by DCKT** [green-labs/ppx_spice#70]
Hello !

I'm currently migrating from decco and have a use-case where my enum is lower cased  (like in the example).
I'm not sure that is really a bug tbh, but the workaround is to create a custom encoder at the moment. 

```reason
@spice
type language =
  | ReScript(string) // <- with the argument
  | @spice.as("ocaml") OCaml
  | TypeScript
  | JavaScript

@spice
type user = {
  id: int,
  nickname?: string,
  language: language,
}

let data = %raw(`
  {
    "id": 1,
    "nickname": "bob",
    "language": ["ocaml"] // <- This is the array
  }
`)

Js.log(data->user_decode)
```

The ouput :

```bash
Error while running external preprocessor
Fatal error: exception Failure("Partial @spice.as usage is not allowed")
```bash

Thanks for your work :)

**Comment by mununki** [comment]
Hi, thank you for opening the issue.
Yes, spice does not support variant arguments, that's what makes it different from decco. In fact, that was the motivation for creating spice in the first place. https://github.com/green-labs/ppx_spice#motivation

FYI, decco defines an array of json values corresponding to variants and (d)serializes them as arguments to variants. Instead, spice (d)serializes string values against variants, so it doesn't support variant's argument by design.

As you said, there is a way to create a custom codec.
